// require('./reducers/reducers.test.js')
require('./reducers/toggle_attending_reducer.test.js')
// require('./api/service_users_test.js')
// require('./api/nhs_test.js')
// require('./api/events_test.js')
